name: Linux Tests

on: [push]

jobs:
  TestsCoverage:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Update apt
      run: sudo apt-get update

    - name: Install ninja toolchain
      run: sudo apt-get install -y ninja-build

    - name: Install lcov
      run: sudo apt-get install -y lcov

    - name: Install google test
      run: sudo apt-get install -y libgtest-dev
 
    - name: Install SDL2
      run: sudo apt-get install -y libsdl2-2.0-0 libsdl2-dev

    - name: Install Vulkan
      run: sudo apt-get install -y libvulkan-dev libvulkan1 mesa-vulkan-drivers vulkan-tools vulkan-utils vulkan-validationlayers vulkan-validationlayers-dev

    - name: Debug Vulkan
      run: cat /usr/include/vulkan/vulkan_core.h

    - name: Build then run test and coverage
      working-directory: ${{github.workspace}}
      shell: bash
      env:
       CC:   gcc-10
       CXX:  g++-10
      run: make run_coverage

    - name: Upload general coverage
      working-directory: ${{github.workspace}}
      shell: bash
      run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
