name: Linux Tests

on: [push]

jobs:
  TestsCoverage:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Update apt
      run: sudo apt-get update

    - name: Install ninja toolchain
      run: sudo apt-get install -y ninja-build

    - name: Install lcov
      run: sudo apt-get install -y lcov

    - name: Install google test
      run: sudo apt-get install -y libgtest-dev

    - name: Install SDL2
      run: sudo apt-get install -y libsdl2-2.0-0 libsdl2-dev

    - name: Install Vulkan
      run: sudo apt-get install -y libvulkan-dev libvulkan1 mesa-vulkan-drivers vulkan-tools vulkan-utils vulkan-validationlayers vulkan-validationlayers-dev

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: make coverage

    # Core
    - name: Run Core tests
      id: CoreTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_core_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Core coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: CoreCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.CoreTests.outputs.Coverage }}
        COLOR: ${{ steps.CoreTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Audio
    - name: Run Audio tests
      id: AudioTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_audio_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Audio coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: AudioCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.AudioTests.outputs.Coverage }}
        COLOR: ${{ steps.AudioTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Meta
    - name: Run Meta tests
      id: MetaTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_meta_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Meta coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: MetaCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.MetaTests.outputs.Coverage }}
        COLOR: ${{ steps.MetaTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Flow
    - name: Run Flow tests
      id: FlowTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_flow_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Flow coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: FlowCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.FlowTests.outputs.Coverage }}
        COLOR: ${{ steps.FlowTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Graphics
    - name: Run Graphics tests
      id: GraphicsTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_graphics_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Graphics coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: GraphicsCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.GraphicsTests.outputs.Coverage }}
        COLOR: ${{ steps.GraphicsTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Object
    - name: Run Object tests
      id: ObjectTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_object_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Object coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: ObjectCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.ObjectTests.outputs.Coverage }}
        COLOR: ${{ steps.ObjectTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # Interpreter
    - name: Run Interpreter tests
      id: InterpreterTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_interpreter_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Interpreter coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: InterpreterCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.InterpreterTests.outputs.Coverage }}
        COLOR: ${{ steps.InterpreterTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # ECS
    - name: Run ECS tests
      id: ECSTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_ecs_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload ECS coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: ECSCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.ECSTests.outputs.Coverage }}
        COLOR: ${{ steps.ECSTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # UI
    - name: Run UI tests
      id: UITests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_ui_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload UI coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: UICoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.UITests.outputs.Coverage }}
        COLOR: ${{ steps.UITests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Widgets
    - name: Run Widgets tests
      id: WidgetsTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_widgets_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Widgets coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: WidgetsCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.WidgetsTests.outputs.Coverage }}
        COLOR: ${{ steps.WidgetsTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Voxel
    - name: Run Voxel tests
      id: VoxelTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_voxel_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload Voxel coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: VoxelCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.VoxelTests.outputs.Coverage }}
        COLOR: ${{ steps.VoxelTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # App
    - name: Run App tests
      id: AppTests
      if: ${{ always() }}
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CC:  gcc-10
        CXX: g++-10
      run: |
        if make run_app_coverage; then
          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
          echo "::set-output name=Color::green"
          exit 0
        else
          echo "::set-output name=Coverage::Failure"
          echo "::set-output name=Color::red"
          exit 1
        fi

    - name: Upload App coverage
      uses: RubbaBoy/BYOB@v1.2.0
      if: ${{ always() }}
      with:
        NAME: AppCoverage
        LABEL: 'Linux'
        STATUS: ${{ steps.AppTests.outputs.Coverage }}
        COLOR: ${{ steps.AppTests.outputs.Color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
